version: "3.9"

services:
  backend:
    build: ./backend
    container_name: dockerprac-backend
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/dockerprac
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: dockerprac-frontend
    depends_on:
      - backend

  mongo:
    image: mongo:7
    container_name: dockerprac-mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db

  nginx:
    image: nginx:1.27-alpine
    container_name: dockerprac-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  mongo-data:
